/** Declaration file generated by dts-gen */
declare module 'krist-utils' {

    export function hexToBase36(...args: any[]): void;

    export function isValidARecord(...args: any[]): void;

    export function isValidKristAddress(...args: any[]): void;

    export function isValidName(...args: any[]): void;

    export function makeKristWalletAddress(...args: any[]): void;

    export function makeKristWalletPrivatekey(...args: any[]): void;

    export function makeV2Address(pkey: string): string;

    export function parseCommonMeta(...args: any[]): void;

    export function sha256(...args: any[]): void;

}
